source ENV['GEM_SOURCE'] || "https://rubygems.org"

group :development, :test do
  gem 'rake', '0.9.6',		:require => false
  gem 'puppetlabs_spec_helper', :require => false
  gem 'rspec-puppet',           :require => false
  gem 'serverspec',             :require => false
  gem 'puppet-lint',            :require => false
  gem 'pry',                    :require => false
  gem 'simplecov',              :require => false
end
